# Generated by Django 4.1.5 on 2023-01-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faTranslate', models.TextField()),
                ('enTranslate', models.TextField()),
                ('voice', models.FileField(upload_to='')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
